DROP SEQUENCE REVIEW_SEQ ;
DROP SEQUENCE REPORT_SEQ;
DROP SEQUENCE REVIEW_COMMENT_SEQ;
DROP SEQUENCE REVIEW_CO_COMMENT_SEQ;
DROP SEQUENCE TAG_SEQ;
drop table review_co_comment  CASCADE CONSTRAINTS PURGE;
drop table review_comment CASCADE CONSTRAINTS PURGE;
drop table "TAG" CASCADE CONSTRAINTS PURGE;
drop table "REPORT" CASCADE CONSTRAINTS PURGE;
drop table review CASCADE CONSTRAINTS PURGE;



commit;